### ISSUE TITLE
Fault on Homebridge Startup

### ISSUE THREAD

**Issue by davet9713** [potmat/homebridge-google-nest-sdm#1]
After completely configuring Google-side per the instructions, and putting all the very long resulting codes in the json, this happens on startup. Running the Google curl test commands to get device list, etc... all works fine

Error: Request had insufficient authentication scopes.
    at MessageStream._onEnd (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:301:20)
    at MessageStream._onStatus (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:342:12)
    at ClientDuplexStreamImpl.<anonymous> (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:198:38)
    at Object.onceWrapper (events.js:482:26)
    at ClientDuplexStreamImpl.emit (events.js:375:28)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client.ts:675:16)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
which sends Homebridge into a reboot loop...

**Comment by bradhs** [comment]
It took me a while to figure it out.  Sounds like you're missing something in the way you configured it.  Recheck all your steps.

**Comment by davet9713** [comment]
I redid the entire thing from scratch... now I'm at 
 [homebridge-google-nest-sdm] There was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm/blob/master/README.md StatusError: Requested project not found or user does not have access to it (project=592e3e76-5bc9-45b5-b64e-82f30d1f2da3). Make sure to specify the unique project identifier and not the Google Cloud Console display name.
    at MessageStream._onEnd (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:301:20)

I'm able to access the pull subscription that I created from google cloud shell with no error, it returns "Listed 0 items", but there's no error.

**Comment by bradhs** [comment]
That's where I'm at.  Nest icon and not responding.

**Comment by potmat** [comment]
HI @bradhs, usually if the cameras are "not responding" after you view them, there is an error in the log.  If you can let me know what the error is it would be very helpful.

**Comment by bradhs** [comment]
I have both, the battery operated ones and the old school ones. See log entries for both cameras below.

[11/22/2021, 6:25:21 PM] [homebridge-google-nest-sdm] Failed to start stream: spawn ffmpeg ENOENT Garage Camera
[11/22/2021, 6:25:25 PM] [homebridge-google-nest-sdm] Nest battery powered cameras are not supported at this time.  The plugin developer doesn't own one so he can't add support. See https://github.com/potmat/homebridge-google-nest-sdm#homebridge-google-nest-sdm
[11/22/2021, 6:25:27 PM] [homebridge-google-nest-sdm] Failed to start stream: spawn ffmpeg ENOENT Outside Camera
[11/22/2021, 6:25:31 PM] [homebridge-google-nest-sdm] Failed to start stream: spawn ffmpeg ENOENT Outside Camera
[11/22/2021, 6:25:41 PM] [homebridge-google-nest-sdm] Failed to start stream: spawn ffmpeg ENOENT Outside Camera

**Comment by potmat** [comment]
HI @bradhs, we'll the first error is obvious :)

As for the second it looks like ffmpeg is not installed on the device hosting your Homebridge app?

**Comment by bradhs** [comment]
It's installed but I think the issue is the path.  I'm in a Windows environment.  How do I specify path? I'll have a look around at it too.

**Comment by bradhs** [comment]
This is the one installed: Homebridge Camera FFmpeg

**Comment by bradhs** [comment]
I installed ffmpeg and pointed it to the file but still not sure what to do.

**Comment by potmat** [comment]
@bradhs Open a command prompt and type `ffmpeg` if you get something you should be fine, if you get a "command not found" you're still not there :)

**Comment by bradhs** [comment]
[11/22/2021, 7:43:31 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.CameraLiveStream had value {"maxVideoResolution":{"width":640,"height":480},"videoCodecs":["H264"],"audioCodecs":["AAC"],"supportedProtocols":["RTSP"]}
[11/22/2021, 7:43:31 PM] [homebridge-google-nest-sdm] Video stream requested: 1280 x 720, 30 fps, 299 kbps Garage Camera
[11/22/2021, 7:43:31 PM] [homebridge-google-nest-sdm] Executing command sdm.devices.commands.CameraLiveStream.GenerateRtspStream with parameters undefined

**Comment by bradhs** [comment]
Ah, so I probably need to set an env variable or put it in a place where the service can access the executable....

**Comment by bradhs** [comment]
Here's where I'm at...



[11/22/2021, 7:51:32 PM] [homebridge-google-nest-sdm] Video stream requested: 1280 x 720, 30 fps, 299 kbps Outside Camera
[11/22/2021, 7:51:32 PM] [homebridge-google-nest-sdm] Executing command sdm.devices.commands.CameraLiveStream.GenerateRtspStream with parameters undefined
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm] Execution of command sdm.devices.commands.CameraLiveStream.GenerateRtspStream returned {"streamUrls":{"rtspUrl":"rtsps://stream-ue1-bravo.dropcam.com:443/sdm_live_stream/CiUA2vuxrKA?auth=g","expiresAt":"2021-11-23T03:56:33.183Z"}
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm] Stream command: ffmpeg -i rtsps://stream-ue1-bravo.dropcam.com:443/sdm_live_stream/remmoved for security srtp://192.168.100.148:61165?rtcpport=61165&pkt_size=188 -loglevel level+verbose Outside Camera
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm] [info] ffmpeg version 2021-11-22-git-203b0e3561-essentials_build-www.gyan.dev Copyright (c) 2000-2021  Outside Cameralopers
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   built with gcc 11.2.0 (Rev2, Built by MSYS2 project)
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm] [info]   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex  Outside Camerabis --enable-librubberband
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm]  Outside Camera
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavutil      57.  9.100 / 57.  9.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavcodec     59. 13.100 / 59. 13.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavformat    59.  9.101 / 59.  9.101
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavdevice    59.  0.101 / 59.  0.101
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavfilter     8. 17.100 /  8. 17.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libswscale      6.  1.100 /  6.  1.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libswresample   4.  0.100 /  4.  0.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libpostproc    56.  0.100 / 56.  0.100
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm]  Outside Camera
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [tcp @ 00000280aed12640] [verbose] Starting connection attempt to 35.201.67.77 port 443
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm]  Outside Camera
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [tcp @ 00000280aed12640] [verbose] Successfully connected to 35.201.67.77 port 443
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm]  Outside Camera
 Outside Camera51:46 PM] [homebridge-google-nest-sdm] [rtsp @ 00000280aed0e780] [error] method DESCRIBE failed: 404 Not Found
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm]  Outside Camera
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm] [error] rtsps://stream-ue1-bravo.dropcam.com:443/sdm_live_stream/--y0OYy--EbSKA?auth=g.0...bHboUnbtY- Outside CameraLM4B2u2Db4w2Umg: Server returned 404 Not Found
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm]  Outside Camera
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm] FFmpeg exited with code: 1 and signal: null (Error) Outside Camera
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm] Executing command sdm.devices.commands.CameraLiveStream.StopRtspStream with parameters {"streamExtensionToken":"--oSrj"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Execution of command sdm.devices.commands.CameraLiveStream.StopRtspStream returned undefined
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Stopped video stream. Outside Camera
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentHeatingCoolingState
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatHvac had value {"status":"OFF"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TargetHeatingCoolingState
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatMode had value {"mode":"OFF","availableModes":["HEAT","COOL","HEATCOOL","OFF"]}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Temperature had value {"ambientTemperatureCelsius":24.68999}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TargetTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatEco had value {"availableModes":["OFF","MANUAL_ECO"],"mode":"OFF","heatCelsius":16.66698,"coolCelsius":27.98012}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TemperatureDisplayUnits
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Settings had value {"temperatureScale":"FAHRENHEIT"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Humidity had value {"ambientHumidityPercent":36}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentHeatingCoolingState
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatHvac had value {"status":"OFF"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TargetHeatingCoolingState
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatMode had value {"mode":"OFF","availableModes":["HEAT","COOL","HEATCOOL","OFF"]}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Temperature had value {"ambientTemperatureCelsius":25.18999}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TargetTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatEco had value {"availableModes":["OFF","MANUAL_ECO"],"mode":"OFF","heatCelsius":16.66997,"coolCelsius":27.87894}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TemperatureDisplayUnits
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Settings had value {"temperatureScale":"FAHRENHEIT"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Humidity had value {"ambientHumidityPercent":37}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatTemperatureSetpoint had value {}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatTemperatureSetpoint had value {}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatMode had value {"mode":"OFF","availableModes":["HEAT","COOL","HEATCOOL","OFF"]}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatMode had value {"mode":"OFF","availableModes":["HEAT","COOL","HEATCOOL","OFF"]}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (C:\Users\administrator.SCS.000\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2074:105)
    at TargetTemperature.Characteristic.validateUserInput (C:\Users\administrator.SCS.000\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1927:14)
    at TargetTemperature.<anonymous> (C:\Users\administrator.SCS.000\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1492:24)
    at step (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:124:57)
    at fulfilled (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2074:105)
    at TargetTemperature.Characteristic.validateUserInput (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1927:14)
    at TargetTemperature.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1492:24)
    at step (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:124:57)
    at fulfilled (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by bradhs** [comment]
Here's where I'm at:


[11/22/2021, 7:51:32 PM] [homebridge-google-nest-sdm] Video stream requested: 1280 x 720, 30 fps, 299 kbps Outside Camera
[11/22/2021, 7:51:32 PM] [homebridge-google-nest-sdm] Executing command sdm.devices.commands.CameraLiveStream.GenerateRtspStream with parameters undefined
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm] Execution of command sdm.devices.commands.CameraLiveStream.GenerateRtspStream returned {"streamUrls":{"rtspUrl":"rtsps://stream-ue1-bravo.dropcam.com:443/sdm_live_stream/CiUA2vuxrKA?auth=g","expiresAt":"2021-11-23T03:56:33.183Z"}
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm] Stream command: ffmpeg -i rtsps://stream-ue1-bravo.dropcam.com:443/sdm_live_stream/remmoved for security srtp://192.168.100.148:61165?rtcpport=61165&pkt_size=188 -loglevel level+verbose Outside Camera
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm] [info] ffmpeg version 2021-11-22-git-203b0e3561-essentials_build-www.gyan.dev Copyright (c) 2000-2021  Outside Cameralopers
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   built with gcc 11.2.0 (Rev2, Built by MSYS2 project)
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm] [info]   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex  Outside Camerabis --enable-librubberband
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm]  Outside Camera
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavutil      57.  9.100 / 57.  9.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavcodec     59. 13.100 / 59. 13.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavformat    59.  9.101 / 59.  9.101
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavdevice    59.  0.101 / 59.  0.101
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libavfilter     8. 17.100 /  8. 17.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libswscale      6.  1.100 /  6.  1.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libswresample   4.  0.100 /  4.  0.100
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [info]   libpostproc    56.  0.100 / 56.  0.100
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm]  Outside Camera
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [tcp @ 00000280aed12640] [verbose] Starting connection attempt to 35.201.67.77 port 443
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm]  Outside Camera
 Outside Camera51:33 PM] [homebridge-google-nest-sdm] [tcp @ 00000280aed12640] [verbose] Successfully connected to 35.201.67.77 port 443
[11/22/2021, 7:51:33 PM] [homebridge-google-nest-sdm]  Outside Camera
 Outside Camera51:46 PM] [homebridge-google-nest-sdm] [rtsp @ 00000280aed0e780] [error] method DESCRIBE failed: 404 Not Found
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm]  Outside Camera
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm] [error] rtsps://stream-ue1-bravo.dropcam.com:443/sdm_live_stream/--y0OYy--EbSKA?auth=g.0...bHboUnbtY- Outside CameraLM4B2u2Db4w2Umg: Server returned 404 Not Found
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm]  Outside Camera
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm] FFmpeg exited with code: 1 and signal: null (Error) Outside Camera
[11/22/2021, 7:51:46 PM] [homebridge-google-nest-sdm] Executing command sdm.devices.commands.CameraLiveStream.StopRtspStream with parameters {"streamExtensionToken":"--oSrj"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Execution of command sdm.devices.commands.CameraLiveStream.StopRtspStream returned undefined
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Stopped video stream. Outside Camera
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentHeatingCoolingState
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatHvac had value {"status":"OFF"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TargetHeatingCoolingState
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatMode had value {"mode":"OFF","availableModes":["HEAT","COOL","HEATCOOL","OFF"]}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Temperature had value {"ambientTemperatureCelsius":24.68999}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TargetTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatEco had value {"availableModes":["OFF","MANUAL_ECO"],"mode":"OFF","heatCelsius":16.66698,"coolCelsius":27.98012}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TemperatureDisplayUnits
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Settings had value {"temperatureScale":"FAHRENHEIT"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Humidity had value {"ambientHumidityPercent":36}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentHeatingCoolingState
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatHvac had value {"status":"OFF"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TargetHeatingCoolingState
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatMode had value {"mode":"OFF","availableModes":["HEAT","COOL","HEATCOOL","OFF"]}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Temperature had value {"ambientTemperatureCelsius":25.18999}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TargetTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatEco had value {"availableModes":["OFF","MANUAL_ECO"],"mode":"OFF","heatCelsius":16.66997,"coolCelsius":27.87894}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET TemperatureDisplayUnits
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Settings had value {"temperatureScale":"FAHRENHEIT"}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Triggered GET CurrentTemperature
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.Humidity had value {"ambientHumidityPercent":37}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatTemperatureSetpoint had value {}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatTemperatureSetpoint had value {}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatMode had value {"mode":"OFF","availableModes":["HEAT","COOL","HEATCOOL","OFF"]}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Request for trait sdm.devices.traits.ThermostatMode had value {"mode":"OFF","availableModes":["HEAT","COOL","HEATCOOL","OFF"]}
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2074:105)
    at TargetTemperature.Characteristic.validateUserInput (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1927:14)
    at TargetTemperature.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1492:24)
    at step (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:124:57)
    at fulfilled (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[11/22/2021, 7:51:47 PM] [homebridge-google-nest-sdm] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2074:105)
    at TargetTemperature.Characteristic.validateUserInput (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1927:14)
    at TargetTemperature.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1492:24)
    at step (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:124:57)
    at fulfilled (C:\Users\myuser\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by potmat** [comment]
`Outside Camera51:46 PM] [homebridge-google-nest-sdm] [rtsp @ 00000280aed0e780] [error] method DESCRIBE failed: 404 Not Found`

I get this one too sometimes, it seems random, I can't account for it at this time...

**Comment by potmat** [comment]
Closed the issue in favour of a new one:

https://github.com/potmat/homebridge-google-nest-sdm/issues/4
