### ISSUE TITLE
Error with event subscription stating Invalid resource name.

### ISSUE THREAD

**Issue by Adelgiorno92** [potmat/homebridge-google-nest-sdm#102]
I have gone through the entire setup process 4 times now. It is now showing up in HomeKit after I removed the child bridge. I even completely removed the cache devices before that and then uninstalled and reinstalled the whole plugin before the most recent attempt. But it is still throwing this error. I have clearly gone through the steps and even made sure to use the + link you provided, turned on Cloud Pub/Sub and added the GCP Project ID using the Project ID. Not sure if there is some functionality lost yet since I have been playing with it all day. Any thoughts on how I can clear this error?

#[homebridge-google-nest-sdm] Plugin initialization failed, there was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from StatusError: Invalid resource name given (name=projects/sdm-prod/topics/enterprise-9b158fa0-6df3-4f1b-9dce-68397594a6bf). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.
    at MessageStream._onEnd (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:289:20)
    at MessageStream._onStatus (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:330:12)
    at ClientDuplexStreamImpl.<anonymous> (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:184:38)
    at Object.onceWrapper (node:events:628:26)
    at ClientDuplexStreamImpl.emit (node:events:513:28)
    at Object.onReceiveStatus (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client.ts:695:16)
    at Object.onReceiveStatus (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 3,
  details: 'Invalid resource name given (name=projects/sdm-prod/topics/enterprise-9b158fa0-6df3-4f1b-9dce-68397594a6bf). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }

**Comment by Ben-Chapman** [comment]
I ran into this same issue, and you're using the Pub/Sub topic name, when you need to use the Pub/Sub *Subscription* Name `¯\_(ツ)_/¯`

- Go to the [Pub/Sub landing page](https://console.cloud.google.com/cloudpubsub/subscription/list)
- Click on the Pub/Sub subscription you created as part of this install process
- At the top of the Subscription landing page, you'll see three pieces of information:
  - Subscription name  <-- This is the value you want to copy/paste into your Homebridge configuration
  - Subscription state
  - Topic name  <-- This is what you have in your Homebridge configuration now, and needs to be replaced.

I hope this helps!

**Comment by potmat** [comment]
@Ben-Chapman is right, as the readme and config screen say, the value should look like

```projects/your-gcp-project-id/subscriptions/your-subscription-id```
