### ISSUE TITLE
nest sdm fails to start

### ISSUE THREAD

**Issue by kamaldeepdhiman** [potmat/homebridge-google-nest-sdm#152]
[2/14/2024, 6:51:44 PM] [homebridge-google-nest-sdm] Plugin initialization failed, there was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from StatusError: Invalid resource name given (name=projects/sdm-prod/topics/enterprise-e49afb10-63e8-40c8-9ce2-b3bf758a89dc). Refer to https://cloud.google.com/pubsub/docs/pubsub-basics#resource_names for more information.
    at MessageStream._onEnd (/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:289:20)
    at MessageStream._onStatus (/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:330:12)
    at ClientDuplexStreamImpl.<anonymous> (/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:184:38)
    at Object.onceWrapper (node:events:632:26)
    at ClientDuplexStreamImpl.emit (node:events:517:28)
    at Object.onReceiveStatus (/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client.ts:695:16)
    at Object.onReceiveStatus (/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 3,
  details: 'Invalid resource name given (name=projects/sdm-prod/topics/enterprise-e49afb10-63e8-40c8-9ce2-b3bf758a89dc). Refer to https://cloud.google.com/pubsub/docs/pubsub-basics#resource_names for more information.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by kamaldeepdhiman** [comment]
All good find solution

**Comment by potmat** [comment]
@kamaldeepdhiman: I don't understand, you figured out the problem?

**Comment by kamaldeepdhiman** [comment]
Mate, I was using gcp cloud wrong I'd
