### ISSUE TITLE
Crash each time I try to access via homekit

### ISSUE THREAD

**Issue by cuni0716** [potmat/homebridge-google-nest-sdm#182]
**Have you read the [FAQ](https://github.com/potmat/homebridge-google-nest-sdm#faq)?**

Yes

**Have you searched [existing issues](https://github.com/potmat/homebridge-google-nest-sdm/issues?q=is%3Aissue)?**

Yes

**Have you searched [existing discussions](https://github.com/potmat/homebridge-google-nest-sdm/discussions?discussions_q=)?**

Yes

**Describe the bug**
Each time I try to access the camera via Apple Homekit app I can see a big error in the homebridge ui and the camera does't respond

**Attach Logs**
```TypeError: Cannot read properties of undefined (reading 'mediaSessionId')
    at WebRtcNestStreamer.initialize (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/NestStreamer.ts:109:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DoorbellStreamingDelegate.startStream (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/StreamingDelegate.ts:300:20)```

**Environment**
Bridged mode

**Comment by potmat** [comment]
Please enable debug mode and post more logs from when you try to view the stream

**Comment by potmat** [comment]
Closing due to lack of activity.
