### ISSUE TITLE
Plugin initialization failed, there was a failure with event subscription

### ISSUE THREAD

**Issue by psdl-dev** [potmat/homebridge-google-nest-sdm#67]
Did everything and then this. I can see my Nest Doorbell, but i don't get what is wrong ?!

[05/02/2023, 20:05:54] [homebridge-google-nest-sdm] Plugin initialization failed, there was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from StatusError: Request had insufficient authentication scopes.
    at MessageStream._onEnd (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:289:20)
    at MessageStream._onStatus (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:330:12)
    at ClientDuplexStreamImpl.<anonymous> (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:184:38)
    at Object.onceWrapper (node:events:628:26)
    at ClientDuplexStreamImpl.emit (node:events:513:28)
    at Object.onReceiveStatus (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client.ts:695:16)
    at Object.onReceiveStatus (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 7,
  details: 'Request had insufficient authentication scopes.',
  metadata: Metadata {
    internalRepr: Map(3) {
      'google.rpc.errorinfo-bin' => [Array],
      'grpc-status-details-bin' => [Array],
      'www-authenticate' => [Array]
    },
    options: {}
  }
}
[05/02/2023, 20:05:56] [homebridge-google-nest-sdm] Restoring existing accessory from cache: Eingang Doorbell

**Comment by psdl-dev** [comment]
Found it. In the SDM API not all scopes were active because the page had more than 25 (50 100) scopes to be activated.

**Comment by psdl-dev** [comment]
Found it. In the SDM API not all scopes were active because the page had more than 25 (50 100) scopes to be activated.
