### ISSUE TITLE
Cannot read properties of undefined (reading 'mediaSessionId')

### ISSUE THREAD

**Issue by luiscarlosgzaa99** [potmat/homebridge-google-nest-sdm#69]
I'm trying to use a new Google Nest Doorbell (wired) but get a G logo and when accessing for live view i get a "No Response" error.

My Homebridge logs throws me this error. Sorry I'm not an expert in this topic

[homebridge-google-nest-sdm] TypeError: Cannot read properties of undefined (reading 'mediaSessionId')
    at WebRtcNestStreamer.initialize (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/NestStreamer.ts:108:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DoorbellStreamingDelegate.startStream (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/StreamingDelegate.ts:300:20)

**Comment by potmat** [comment]
Seems like the RTC stream cannot be setup.  Enable debug mode and look in the logs for something like

`Executing command sdm.devices.commands.CameraLiveStream.GenerateWebRtcStream`

followed by 

`Execution of command sdm.devices.commands.CameraLiveStream.GenerateWebRtcStream`

**Comment by potmat** [comment]
Closing due to lack of activity.
