### ISSUE TITLE
Doorbell Camera not showing properly

### ISSUE THREAD

**Issue by nefariouslegion** [potmat/homebridge-google-nest-sdm#89]
Hi, I just finally got this plugin set up. But when I try to view the doorbell camera in the Home app I just see this nest logo. Any idea how to fix it? 

![IMG_0153](https://github.com/potmat/homebridge-google-nest-sdm/assets/89366675/93e179cc-5d83-4918-b5d9-a3a3c04d8889)

If I then tap on the camera it tries to load for a bit and then just says "No Response This Camera is not responding". So idk why it isn't working

EDIT: Just read about this in the FAQ section but I still don't fully understand it. So are we not supposed to be able to see a live feed of the camera? I ask this because I know the other plugin, Homebridge Nest Cam, can show the live video feed. So I assumed this plugin would do the same

**Comment by potmat** [comment]
Are there any errors in the log when you try to view the stream?

**Comment by nefariouslegion** [comment]
@potmat No, nothing at all shows up in the log when I try to view the stream.

**Comment by potmat** [comment]
Try turning on debug mode in the settings.

![](https://user-images.githubusercontent.com/3979615/77287677-3dbbe700-6d2a-11ea-834f-660ddbc845ab.png)

**Comment by nefariouslegion** [comment]
Ok I turned on debug mode. But I'm not exactly sure how to get the log file out of a Hyper-V VM? The Homebridge UI doesn't let me just copy from the log window unfortunately. Also prior to turning on debug mode I saw this randomly pop up in the homebridge UI log so I took a screenshot of it
![image](https://github.com/potmat/homebridge-google-nest-sdm/assets/89366675/98941e73-436d-49e5-befb-18ce7ba1bd3d)

**Comment by potmat** [comment]
That's unrelated, it encountered a problem downloading an image preview.

> The Homebridge UI doesn't let me just copy from the log window

That's odd, just take a screenshot I guess.

**Comment by nefariouslegion** [comment]
> That's odd, just take a screenshot I guess.

Actually I figured out there was a download button to save the logs. I just didn't notice it before. Here is the log from the time Homebridge starts up all the way to me attempting to view the camera in the home app. 
[homebridge.log.txt](https://github.com/potmat/homebridge-google-nest-sdm/files/12176077/homebridge.log.txt)

**Comment by potmat** [comment]
I don't see any problems.  I can see the stream working just fine starting around line 2359.  You appear to watch the stream for about 30s then stop. I don't see the text:

`ffmpeg exited with code: 1 and signal:null (Error) Front Door Doorbell`

anywhere

**Comment by nefariouslegion** [comment]
> ffmpeg exited with code: 1 and signal:null (Error) Front Door Doorbell

For some reason this error only sometimes comes up. But also even though the log shows me watching the stream I couldn't actually. All I saw was the nest logo followed by "No response" in the home app. So idk why it isn't working?

**Comment by potmat** [comment]
Maybe one of these from the FAQ:

![image](https://github.com/potmat/homebridge-google-nest-sdm/assets/7747977/2e98c5d1-1e1c-4ac7-8331-dc5398cdaa01)

**Comment by nefariouslegion** [comment]
I suppose the first one is similar to my setup. I have homebridge running in a Hyper-V VM. I’m not sure if it’s considered docker though. I think it’s linux (ubuntu) in the VM. So maybe that’s the issue?
________________________________

**Comment by prashanthpk30** [comment]
I have the same issue . I have installed in raspberry pi connected with my home network . Below is what showing to me,

![image](https://github.com/potmat/homebridge-google-nest-sdm/assets/99110177/b2d82c8b-5747-4172-8220-3dc914ab1d90)

**Comment by potmat** [comment]
@nefariouslegion :  I'm not sure.  It seems there is something in your network configuration that is preventing the video stream from being received by your phone.  Without being physically in your house there's really no way for me to know what it is.

@prashanthpk30 : I don't understand, what's the problem here?

**Comment by prashanthpk30** [comment]
@potmat Im getting G logo every time no feed even if I click it video is not coming

**Comment by nefariouslegion** [comment]
Found more errors with the plugin in my latest log file. Not sure if any of these help identify the issue:
`[7/27/2023, 1:03:47 PM] [homebridge-google-nest-sdm] Error terminating SDM stream: TypeError: Cannot read properties of undefined (reading 'streamer') Front Door Doorbell


[7/27/2023, 1:31:44 PM] [homebridge-google-nest-sdm] Could not execute event image GET request:  {"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n    at settle (/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/axios/lib/adapters/http.js:570:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Basic g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJuZXN0LXNlY3VyaXR5LWF1dGhwcm94eSIsInN1YiI6Im5lc3RfaWQ6bmVzdC1waG9lbml4LXByb2Q6MjU3NDM4NDUiLCJwb2wiOiIzcC1vYXV0aC1zY29wZS1BUElfU0RNX1NFUlZJQ0UtY2xpZW50LTEwMzI3ODAwNTIyMzgtMDFiMnIxOWFxMDRpYjdrb28yaGZjZDNta2Znc242dmguYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJleHAiOjE2OTA0NzkxMjB9.dMKAsLU0xlZExLT22bzo9pZVTfWpsY7mLi9SmsYY_aQzM5knHQYFuGdHse7Ko2k2HFwXQkcEv8H3dFEYadBy2mGAnBMeJ5nMIIVLvARqRanGqJhdpBotpBcgmJJTYGr9FTPZkgfynlmsOD0aqmJ2wmNWsmRIZWowvku_u7aktvzVRIRrVKQoFQisJU-XynAa64fp3mxWuTTUUZoBoMBp0LhtUBL3FeGYcVWg4RbJUpTkHDlSBj-KzFWKfMnyiObrDGUiaPv2rSQPQTQMjSv0p-RaJ3C4eTuarx1WUDoZC68xOlPF8hJICfa5O9PUd5cMcZuzKSsFcOZEw0gin8vIqg","User-Agent":"axios/1.4.0","Accept-Encoding":"gzip, compress, deflate, br"},"responseType":"arraybuffer","method":"get","url":"https://nexusapi-us1.dropcam.com/sdm_resource/CiUA2vuxrx8vlnRk89QyMLN-aosKm8oCq0sRfStfn583Scz4hQaPEsEBAOdDZOWMVLLkDf_lUM51dDZrX95bCPfv90lpcR9ER1bp6gA8eWRX0BAGie1XMuefNFkuLyZ8ItgDxOtaO13sZiIrVlTfGiSNYFgBots2Ucx95A_XKaQGOIhw6kSDgoNbURdTNbcaxCR_5L7otkOwkYDb0LTi-ZRH6jNUjD708iv5YlaF70peF1CdLzjiyLW64AEZOx3zG2UoRmk-4au7y6d21vxWmxTapPHUtDVFFtt4MlMnsKN7QH8WZwSLyMMNvg/snapshot"},"code":"ERR_BAD_RESPONSE","status":500} Front Door Doorbell
`

**Comment by potmat** [comment]
@nefariouslegion : First one probably had more errors/warnings preceding it that would identify the problem.

Second one is not related to video streams, but if it keeps happening does point to something strange in your configuration.

**Comment by nefariouslegion** [comment]
@potmat here's the whole log file. I don't see any errors preceeding the first one though

[homebridge.log (2).txt](https://github.com/potmat/homebridge-google-nest-sdm/files/12186818/homebridge.log.2.txt)

**Comment by potmat** [comment]
@nefariouslegion : I notice you're running the plugin in an child bridge.  What if you don't do that?

**Comment by nefariouslegion** [comment]
Oh that was temporary for testing. All previous attempts to get it working were as a non-child bridge
________________________________

**Comment by potmat** [comment]
@nefariouslegion : The only last thing I can think of is that maybe it has something to do with the two nest plugins blocking each other somehow? That's pretty left field though.

Other than that the only thing I can think of is that's it's something to do with the hyper-v VM setup.

**Comment by nefariouslegion** [comment]
I had the same thought about the 2 camera plugins conflicting. But I already tried disabling the other one and it still didn’t fix the issue.

Hmm when I setup the Hyper-V VM I followed the directions from this github https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10-Using-Hyper-V
________________________________

**Comment by potmat** [comment]
@nefariouslegion : Try running Homebridge directly on your windows machine, or on some other box directly connected to the network.  If that fixes it then it's something to do with the networking between your network, host os, hyper-v, and virtualized os.  What that "something" is I have no way to check as I don't have this setup (I don't even own a Windows PC).

**Comment by nefariouslegion** [comment]
@potmat I haven't tried running natively yet (mainly cause I'd have to re-setup my whole home again). But one thing I did notice is that when someone rang the doorbell I still got a notification with picture. So it seems the issue is just trying to stream the live feed. Seems weird to me.

**Comment by potmat** [comment]
> Seems weird to me.

Not really, video streams work very differently than synchronous request/response events like a doorbell ring, potentially even using a totally different transport mechanism (UDP vs. TCP).  It's entirely plausible that one could work while the other doesn't.

**Comment by nefariouslegion** [comment]
> I don't know if that's strictly true. There's nothing stopping you from adding multiple Homebridges to your home. Especially if it's just for testing.

Well I went ahead and setup a temporary homebridge running natively on my Windows 11 PC. But the same issue still persists. I see the nest logo on the Home app main screen. And if I tap it to try and view the live feed I get the "No Response" message

**Comment by potmat** [comment]
The Nest logo is the correct behaviour, see the [FAQ](https://github.com/potmat/homebridge-google-nest-sdm#faq)

As for the "no response" I'm afraid you've got me beat, there's nothing in the log showing any problem.  I don't have any other suggestions to offer.

**Comment by potmat** [comment]
Closing due to lack of activity.
