### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by fbmg** [potmat/homebridge-google-nest-sdm#97]
Hi I get this error on different times ...

[04/09/2023, 11:48:00] [homebridge-google-nest-sdm] Could not execute event image GET request:  {"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n    at settle (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/axios/lib/adapters/http.js:570:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Basic g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJuZXN0LXNlY3VyaXR5LWF1dGhwcm94eSIsInN1YiI6Im5lc3RfaWQ6bmVzdC1waG9lbml4LXByb2Q6OTkyMjcyIiwicG9sIjoiM3Atb2F1dGgtc2NvcGUtQVBJX1NETV9TRVJWSUNFLWNsaWVudC00ODEyNDI2MDA5MjYtZHIzZjdnYmZqazNwcHBqamQ2N2FjcHFxZzhkZXUzbTMuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJleHAiOjE2OTM4MjA5MDZ9.j1dh3VK8qoKzXWP_ci0bEv0zveF1_2sELZp8CMWuQcWcxKLbeC3sTJMzea0iYIW_IjkzuVFuAI2UTZJAlfS6cADNym3GiV91IogFIeDaj14nssXRYLRwokE6Wh4yn8bvyJ25FOJknpIhHQCyy9aV1WBgLPNd8yHcrY2S_xkcsVSPeYHsqK2yy6dPSFYsxzCMvoY8X73_p9m-LuZAJn2UJp77hdlj0s4zLeFWoPfdDw27nGGQY7JAzoILJ19IzWtFMUm7FRwFDmttQAuLh0knmeilmTwfJXUUpxIFPdUyhNmtaJ1uQNVbQQlftSxwZZxCWpYAU-zq650jV2OoTYyXyw","User-Agent":"axios/1.4.0","Accept-Encoding":"gzip, compress, deflate, br"},"responseType":"arraybuffer","method":"get","url":"https://nexusapi-eu1.dropcam.com/sdm_resource/CiUA2vuxr_htyvdY2mrkGDx56XBXA3jQVmBmphzSyFEEJd38M595Eo0BACUE0sLxj8QKXgpVooF1FDk63H_poZswFGZe5jgnWsmlb-gGO48Zi4hmm2luzgoNqzdGOOUrbr1p9lW4HVlNRZyyJ_Q-zheEeOnf4D3Q9SyU6RTuz9AIgJzhZ4Wz6wkhKyZyVnMLDBZ4ucNDfkRURzBOoE8NnWb_ywGSE4pY0g1qrW4MJ8ROFi1ySGJf/snapshot"},"code":"ERR_BAD_RESPONSE","status":500} Slaapkamer voor Camera
[04/09/2023, 18:01:46] [homebridge-google-nest-sdm] FFmpeg exited with code: 1 and signal: null (Error) Slaapkamer voor Camera

**Comment by potmat** [comment]
@fbmg:  Google seems to be throwing an internal error when you try to retrieve event images.

The only thing I can think of is that when you went through the setup process and had to choose which nest devices to grant access to, was there a permission for seeing images?

**Comment by fbmg** [comment]
Hi
No I haven't seen anything about images. This error is no every 1/2 hour in the logfile ?

**Comment by potmat** [comment]
Check if v1.1.20 resolves this issue.

**Comment by potmat** [comment]
Closing due to lack of activity.
